// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwieuwakfivewyyyougo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aWV1d2FrZml2ZXd5eXlvdWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDM5NjksImV4cCI6MjA3MDkxOTk2OX0.MsFp--8AOjWW1gWsvFbPwWObbuC-WfkYVKuzOYxfNd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});